# coding: utf-8

"""
    Investor API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.account_dashboard_controller_api import AccountDashboardControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountDashboardControllerApi(unittest.TestCase):
    """AccountDashboardControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.account_dashboard_controller_api.AccountDashboardControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_time_transaction_summary_using_get(self):
        """Test case for get_all_time_transaction_summary_using_get

        Get all-time transaction summary for current client  # noqa: E501
        """
        pass

    def test_get_expected_cash_flows_for_period_using_post(self):
        """Test case for get_expected_cash_flows_for_period_using_post

        Get the cash flows expected by the current client for the next four weeks (28 days)  # noqa: E501
        """
        pass

    def test_get_funds_in_transit_summary_by_loan_originator_using_post(self):
        """Test case for get_funds_in_transit_summary_by_loan_originator_using_post

        Get funds in transit summary by loan originator for current client  # noqa: E501
        """
        pass

    def test_get_investment_summary_by_country_using_post(self):
        """Test case for get_investment_summary_by_country_using_post

        Get investment summary by country for current client and given filter  # noqa: E501
        """
        pass

    def test_get_investment_summary_by_interest_using_post(self):
        """Test case for get_investment_summary_by_interest_using_post

        Get investment summary by interest for current client and given filter  # noqa: E501
        """
        pass

    def test_get_investment_summary_by_loan_originator_using_post(self):
        """Test case for get_investment_summary_by_loan_originator_using_post

        Get investment summary by loan originator for current client and given filter  # noqa: E501
        """
        pass

    def test_get_investment_summary_by_loan_status_using_post(self):
        """Test case for get_investment_summary_by_loan_status_using_post

        Get investment summary by loan status for current client and given filter  # noqa: E501
        """
        pass

    def test_get_investment_summary_by_loan_type_using_post(self):
        """Test case for get_investment_summary_by_loan_type_using_post

        Get investment summary by loan type for current client and given filter  # noqa: E501
        """
        pass

    def test_get_investment_summary_by_maturity_using_post(self):
        """Test case for get_investment_summary_by_maturity_using_post

        Get investment summary by maturity for current client and given filter  # noqa: E501
        """
        pass

    def test_get_outstanding_balance_using_get(self):
        """Test case for get_outstanding_balance_using_get

        Get outstanding balance for current client  # noqa: E501
        """
        pass

    def test_get_xirr_using_post(self):
        """Test case for get_xirr_using_post

        Calculate XIRR for current client and given filter  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
