# coding: utf-8

"""
    Investor API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.password_controller_api import PasswordControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPasswordControllerApi(unittest.TestCase):
    """PasswordControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.password_controller_api.PasswordControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_change_password_using_post(self):
        """Test case for change_password_using_post

        changePassword  # noqa: E501
        """
        pass

    def test_reset_password_step1_using_post(self):
        """Test case for reset_password_step1_using_post

        resetPasswordStep1  # noqa: E501
        """
        pass

    def test_reset_password_step2_using_post(self):
        """Test case for reset_password_step2_using_post

        resetPasswordStep2  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
