# coding: utf-8

"""
    Investor API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.country_controller_api import CountryControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCountryControllerApi(unittest.TestCase):
    """CountryControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.country_controller_api.CountryControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_countries_using_get(self):
        """Test case for get_countries_using_get

        getCountries  # noqa: E501
        """
        pass

    def test_get_loan_countries_using_get(self):
        """Test case for get_loan_countries_using_get

        getLoanCountries  # noqa: E501
        """
        pass

    def test_get_originator_countries_using_get(self):
        """Test case for get_originator_countries_using_get

        getOriginatorCountries  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
