# coding: utf-8

"""
    Investor API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.public_investment_controller_api import PublicInvestmentControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPublicInvestmentControllerApi(unittest.TestCase):
    """PublicInvestmentControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.public_investment_controller_api.PublicInvestmentControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_loan_attachment_using_get1(self):
        """Test case for download_loan_attachment_using_get1

        downloadLoanAttachment  # noqa: E501
        """
        pass

    def test_get_primary_market_loan_info_using_get(self):
        """Test case for get_primary_market_loan_info_using_get

        getPrimaryMarketLoanInfo  # noqa: E501
        """
        pass

    def test_list_loan_attachments_using_get(self):
        """Test case for list_loan_attachments_using_get

        listLoanAttachments  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
