# coding: utf-8

"""
    Investor API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.originator_summary_controller_api import OriginatorSummaryControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOriginatorSummaryControllerApi(unittest.TestCase):
    """OriginatorSummaryControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.originator_summary_controller_api.OriginatorSummaryControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_originators_using_get1(self):
        """Test case for get_originators_using_get1

        getOriginators  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
