# coding: utf-8

"""
    Investor API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.client_init_data_controller_api import ClientInitDataControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClientInitDataControllerApi(unittest.TestCase):
    """ClientInitDataControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.client_init_data_controller_api.ClientInitDataControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_init_using_get(self):
        """Test case for init_using_get

        init  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
