# coding: utf-8

"""
    Investor API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AgreementModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'privacy_policy_accepted': 'bool',
        'data_processing_accepted': 'bool'
    }

    attribute_map = {
        'privacy_policy_accepted': 'privacy_policy_accepted',
        'data_processing_accepted': 'data_processing_accepted'
    }

    def __init__(self, privacy_policy_accepted=None, data_processing_accepted=None):  # noqa: E501
        """AgreementModel - a model defined in Swagger"""  # noqa: E501

        self._privacy_policy_accepted = None
        self._data_processing_accepted = None
        self.discriminator = None

        if privacy_policy_accepted is not None:
            self.privacy_policy_accepted = privacy_policy_accepted
        if data_processing_accepted is not None:
            self.data_processing_accepted = data_processing_accepted

    @property
    def privacy_policy_accepted(self):
        """Gets the privacy_policy_accepted of this AgreementModel.  # noqa: E501


        :return: The privacy_policy_accepted of this AgreementModel.  # noqa: E501
        :rtype: bool
        """
        return self._privacy_policy_accepted

    @privacy_policy_accepted.setter
    def privacy_policy_accepted(self, privacy_policy_accepted):
        """Sets the privacy_policy_accepted of this AgreementModel.


        :param privacy_policy_accepted: The privacy_policy_accepted of this AgreementModel.  # noqa: E501
        :type: bool
        """

        self._privacy_policy_accepted = privacy_policy_accepted

    @property
    def data_processing_accepted(self):
        """Gets the data_processing_accepted of this AgreementModel.  # noqa: E501


        :return: The data_processing_accepted of this AgreementModel.  # noqa: E501
        :rtype: bool
        """
        return self._data_processing_accepted

    @data_processing_accepted.setter
    def data_processing_accepted(self, data_processing_accepted):
        """Sets the data_processing_accepted of this AgreementModel.


        :param data_processing_accepted: The data_processing_accepted of this AgreementModel.  # noqa: E501
        :type: bool
        """

        self._data_processing_accepted = data_processing_accepted

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AgreementModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AgreementModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
