# coding: utf-8

"""
    Investor API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BalanceModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'corrections': 'float',
        'earned_so_far': 'float',
        'fit_interest': 'float',
        'funds_available': 'float',
        'funds_in_transit': 'float',
        'funds_invested': 'float',
        'funds_reserved': 'float',
        'total_amount': 'float'
    }

    attribute_map = {
        'corrections': 'corrections',
        'earned_so_far': 'earned_so_far',
        'fit_interest': 'fit_interest',
        'funds_available': 'funds_available',
        'funds_in_transit': 'funds_in_transit',
        'funds_invested': 'funds_invested',
        'funds_reserved': 'funds_reserved',
        'total_amount': 'total_amount'
    }

    def __init__(self, corrections=None, earned_so_far=None, fit_interest=None, funds_available=None, funds_in_transit=None, funds_invested=None, funds_reserved=None, total_amount=None):  # noqa: E501
        """BalanceModel - a model defined in Swagger"""  # noqa: E501

        self._corrections = None
        self._earned_so_far = None
        self._fit_interest = None
        self._funds_available = None
        self._funds_in_transit = None
        self._funds_invested = None
        self._funds_reserved = None
        self._total_amount = None
        self.discriminator = None

        if corrections is not None:
            self.corrections = corrections
        if earned_so_far is not None:
            self.earned_so_far = earned_so_far
        if fit_interest is not None:
            self.fit_interest = fit_interest
        if funds_available is not None:
            self.funds_available = funds_available
        if funds_in_transit is not None:
            self.funds_in_transit = funds_in_transit
        if funds_invested is not None:
            self.funds_invested = funds_invested
        if funds_reserved is not None:
            self.funds_reserved = funds_reserved
        if total_amount is not None:
            self.total_amount = total_amount

    @property
    def corrections(self):
        """Gets the corrections of this BalanceModel.  # noqa: E501


        :return: The corrections of this BalanceModel.  # noqa: E501
        :rtype: float
        """
        return self._corrections

    @corrections.setter
    def corrections(self, corrections):
        """Sets the corrections of this BalanceModel.


        :param corrections: The corrections of this BalanceModel.  # noqa: E501
        :type: float
        """

        self._corrections = corrections

    @property
    def earned_so_far(self):
        """Gets the earned_so_far of this BalanceModel.  # noqa: E501


        :return: The earned_so_far of this BalanceModel.  # noqa: E501
        :rtype: float
        """
        return self._earned_so_far

    @earned_so_far.setter
    def earned_so_far(self, earned_so_far):
        """Sets the earned_so_far of this BalanceModel.


        :param earned_so_far: The earned_so_far of this BalanceModel.  # noqa: E501
        :type: float
        """

        self._earned_so_far = earned_so_far

    @property
    def fit_interest(self):
        """Gets the fit_interest of this BalanceModel.  # noqa: E501


        :return: The fit_interest of this BalanceModel.  # noqa: E501
        :rtype: float
        """
        return self._fit_interest

    @fit_interest.setter
    def fit_interest(self, fit_interest):
        """Sets the fit_interest of this BalanceModel.


        :param fit_interest: The fit_interest of this BalanceModel.  # noqa: E501
        :type: float
        """

        self._fit_interest = fit_interest

    @property
    def funds_available(self):
        """Gets the funds_available of this BalanceModel.  # noqa: E501


        :return: The funds_available of this BalanceModel.  # noqa: E501
        :rtype: float
        """
        return self._funds_available

    @funds_available.setter
    def funds_available(self, funds_available):
        """Sets the funds_available of this BalanceModel.


        :param funds_available: The funds_available of this BalanceModel.  # noqa: E501
        :type: float
        """

        self._funds_available = funds_available

    @property
    def funds_in_transit(self):
        """Gets the funds_in_transit of this BalanceModel.  # noqa: E501


        :return: The funds_in_transit of this BalanceModel.  # noqa: E501
        :rtype: float
        """
        return self._funds_in_transit

    @funds_in_transit.setter
    def funds_in_transit(self, funds_in_transit):
        """Sets the funds_in_transit of this BalanceModel.


        :param funds_in_transit: The funds_in_transit of this BalanceModel.  # noqa: E501
        :type: float
        """

        self._funds_in_transit = funds_in_transit

    @property
    def funds_invested(self):
        """Gets the funds_invested of this BalanceModel.  # noqa: E501


        :return: The funds_invested of this BalanceModel.  # noqa: E501
        :rtype: float
        """
        return self._funds_invested

    @funds_invested.setter
    def funds_invested(self, funds_invested):
        """Sets the funds_invested of this BalanceModel.


        :param funds_invested: The funds_invested of this BalanceModel.  # noqa: E501
        :type: float
        """

        self._funds_invested = funds_invested

    @property
    def funds_reserved(self):
        """Gets the funds_reserved of this BalanceModel.  # noqa: E501


        :return: The funds_reserved of this BalanceModel.  # noqa: E501
        :rtype: float
        """
        return self._funds_reserved

    @funds_reserved.setter
    def funds_reserved(self, funds_reserved):
        """Sets the funds_reserved of this BalanceModel.


        :param funds_reserved: The funds_reserved of this BalanceModel.  # noqa: E501
        :type: float
        """

        self._funds_reserved = funds_reserved

    @property
    def total_amount(self):
        """Gets the total_amount of this BalanceModel.  # noqa: E501


        :return: The total_amount of this BalanceModel.  # noqa: E501
        :rtype: float
        """
        return self._total_amount

    @total_amount.setter
    def total_amount(self, total_amount):
        """Sets the total_amount of this BalanceModel.


        :param total_amount: The total_amount of this BalanceModel.  # noqa: E501
        :type: float
        """

        self._total_amount = total_amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BalanceModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BalanceModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
