# coding: utf-8

"""
    Investor API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BorrowerConsumerModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'age': 'int',
        'country': 'str',
        'dependants': 'int',
        'gender': 'str',
        'income': 'float',
        'liabilities': 'float',
        'loan_count': 'int',
        'marital_status': 'str',
        'occupation': 'str',
        'town': 'str'
    }

    attribute_map = {
        'age': 'age',
        'country': 'country',
        'dependants': 'dependants',
        'gender': 'gender',
        'income': 'income',
        'liabilities': 'liabilities',
        'loan_count': 'loan_count',
        'marital_status': 'marital_status',
        'occupation': 'occupation',
        'town': 'town'
    }

    def __init__(self, age=None, country=None, dependants=None, gender=None, income=None, liabilities=None, loan_count=None, marital_status=None, occupation=None, town=None):  # noqa: E501
        """BorrowerConsumerModel - a model defined in Swagger"""  # noqa: E501

        self._age = None
        self._country = None
        self._dependants = None
        self._gender = None
        self._income = None
        self._liabilities = None
        self._loan_count = None
        self._marital_status = None
        self._occupation = None
        self._town = None
        self.discriminator = None

        if age is not None:
            self.age = age
        if country is not None:
            self.country = country
        if dependants is not None:
            self.dependants = dependants
        if gender is not None:
            self.gender = gender
        if income is not None:
            self.income = income
        if liabilities is not None:
            self.liabilities = liabilities
        if loan_count is not None:
            self.loan_count = loan_count
        if marital_status is not None:
            self.marital_status = marital_status
        if occupation is not None:
            self.occupation = occupation
        if town is not None:
            self.town = town

    @property
    def age(self):
        """Gets the age of this BorrowerConsumerModel.  # noqa: E501


        :return: The age of this BorrowerConsumerModel.  # noqa: E501
        :rtype: int
        """
        return self._age

    @age.setter
    def age(self, age):
        """Sets the age of this BorrowerConsumerModel.


        :param age: The age of this BorrowerConsumerModel.  # noqa: E501
        :type: int
        """

        self._age = age

    @property
    def country(self):
        """Gets the country of this BorrowerConsumerModel.  # noqa: E501


        :return: The country of this BorrowerConsumerModel.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this BorrowerConsumerModel.


        :param country: The country of this BorrowerConsumerModel.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def dependants(self):
        """Gets the dependants of this BorrowerConsumerModel.  # noqa: E501


        :return: The dependants of this BorrowerConsumerModel.  # noqa: E501
        :rtype: int
        """
        return self._dependants

    @dependants.setter
    def dependants(self, dependants):
        """Sets the dependants of this BorrowerConsumerModel.


        :param dependants: The dependants of this BorrowerConsumerModel.  # noqa: E501
        :type: int
        """

        self._dependants = dependants

    @property
    def gender(self):
        """Gets the gender of this BorrowerConsumerModel.  # noqa: E501


        :return: The gender of this BorrowerConsumerModel.  # noqa: E501
        :rtype: str
        """
        return self._gender

    @gender.setter
    def gender(self, gender):
        """Sets the gender of this BorrowerConsumerModel.


        :param gender: The gender of this BorrowerConsumerModel.  # noqa: E501
        :type: str
        """
        allowed_values = ["MALE", "FEMALE"]  # noqa: E501
        if gender not in allowed_values:
            raise ValueError(
                "Invalid value for `gender` ({0}), must be one of {1}"  # noqa: E501
                .format(gender, allowed_values)
            )

        self._gender = gender

    @property
    def income(self):
        """Gets the income of this BorrowerConsumerModel.  # noqa: E501


        :return: The income of this BorrowerConsumerModel.  # noqa: E501
        :rtype: float
        """
        return self._income

    @income.setter
    def income(self, income):
        """Sets the income of this BorrowerConsumerModel.


        :param income: The income of this BorrowerConsumerModel.  # noqa: E501
        :type: float
        """

        self._income = income

    @property
    def liabilities(self):
        """Gets the liabilities of this BorrowerConsumerModel.  # noqa: E501


        :return: The liabilities of this BorrowerConsumerModel.  # noqa: E501
        :rtype: float
        """
        return self._liabilities

    @liabilities.setter
    def liabilities(self, liabilities):
        """Sets the liabilities of this BorrowerConsumerModel.


        :param liabilities: The liabilities of this BorrowerConsumerModel.  # noqa: E501
        :type: float
        """

        self._liabilities = liabilities

    @property
    def loan_count(self):
        """Gets the loan_count of this BorrowerConsumerModel.  # noqa: E501


        :return: The loan_count of this BorrowerConsumerModel.  # noqa: E501
        :rtype: int
        """
        return self._loan_count

    @loan_count.setter
    def loan_count(self, loan_count):
        """Sets the loan_count of this BorrowerConsumerModel.


        :param loan_count: The loan_count of this BorrowerConsumerModel.  # noqa: E501
        :type: int
        """

        self._loan_count = loan_count

    @property
    def marital_status(self):
        """Gets the marital_status of this BorrowerConsumerModel.  # noqa: E501


        :return: The marital_status of this BorrowerConsumerModel.  # noqa: E501
        :rtype: str
        """
        return self._marital_status

    @marital_status.setter
    def marital_status(self, marital_status):
        """Sets the marital_status of this BorrowerConsumerModel.


        :param marital_status: The marital_status of this BorrowerConsumerModel.  # noqa: E501
        :type: str
        """
        allowed_values = ["SINGLE", "MARRIED"]  # noqa: E501
        if marital_status not in allowed_values:
            raise ValueError(
                "Invalid value for `marital_status` ({0}), must be one of {1}"  # noqa: E501
                .format(marital_status, allowed_values)
            )

        self._marital_status = marital_status

    @property
    def occupation(self):
        """Gets the occupation of this BorrowerConsumerModel.  # noqa: E501


        :return: The occupation of this BorrowerConsumerModel.  # noqa: E501
        :rtype: str
        """
        return self._occupation

    @occupation.setter
    def occupation(self, occupation):
        """Sets the occupation of this BorrowerConsumerModel.


        :param occupation: The occupation of this BorrowerConsumerModel.  # noqa: E501
        :type: str
        """

        self._occupation = occupation

    @property
    def town(self):
        """Gets the town of this BorrowerConsumerModel.  # noqa: E501


        :return: The town of this BorrowerConsumerModel.  # noqa: E501
        :rtype: str
        """
        return self._town

    @town.setter
    def town(self, town):
        """Sets the town of this BorrowerConsumerModel.


        :param town: The town of this BorrowerConsumerModel.  # noqa: E501
        :type: str
        """

        self._town = town

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BorrowerConsumerModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BorrowerConsumerModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
