# coding: utf-8

"""
    Investor API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PasswordModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'password1': 'str',
        'password2': 'str'
    }

    attribute_map = {
        'password1': 'password1',
        'password2': 'password2'
    }

    def __init__(self, password1=None, password2=None):  # noqa: E501
        """PasswordModel - a model defined in Swagger"""  # noqa: E501

        self._password1 = None
        self._password2 = None
        self.discriminator = None

        if password1 is not None:
            self.password1 = password1
        if password2 is not None:
            self.password2 = password2

    @property
    def password1(self):
        """Gets the password1 of this PasswordModel.  # noqa: E501


        :return: The password1 of this PasswordModel.  # noqa: E501
        :rtype: str
        """
        return self._password1

    @password1.setter
    def password1(self, password1):
        """Sets the password1 of this PasswordModel.


        :param password1: The password1 of this PasswordModel.  # noqa: E501
        :type: str
        """

        self._password1 = password1

    @property
    def password2(self):
        """Gets the password2 of this PasswordModel.  # noqa: E501


        :return: The password2 of this PasswordModel.  # noqa: E501
        :rtype: str
        """
        return self._password2

    @password2.setter
    def password2(self, password2):
        """Sets the password2 of this PasswordModel.


        :param password2: The password2 of this PasswordModel.  # noqa: E501
        :type: str
        """

        self._password2 = password2

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PasswordModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PasswordModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
